### ISSUE TITLE
Can't laucnh second sector

### ISSUE THREAD

**Issue by AaRCaT** [Sh1penfire/Meld#3]
Missing Copper and Lead
![image](https://github.com/user-attachments/assets/c1e9ff20-6ce8-4316-a591-38d0d34a78fb)

**Comment by Sh1penfire** [comment]
Make a schematic with the raft core, should fix it

**Comment by AaRCaT** [comment]
Oh fixed, thanks
Also you should put schematic in this mod without make it?

**Comment by Sh1penfire** [comment]
Yeah, that's a good reminder
